local language_table = {
	{ "English", "Hello World"},
	{ "Afrikaans", "Hallo Wereld" },
	{ "Albanian", "Pershendetje Bote" },
	{ "Basque", "Kaixo Mundua" },
	{ "Catalan", "Hola Mon" },
	{ "Croatian", "Bok Svijete" },
	{ "Czech", "Ahoj Svete" },
	{ "Danish", "Hej Verden" },
	{ "Dutch", "Hallo Wereld" },
	{ "Esperanto", "Saluton Mondo" },
	{ "Estonian", "Tere Maailm" },
	{ "Finnish", "Hei Maailma" },
	{ "French", "Bonjour Monde" },
	{ "Galician", "Ola Mundo" },
	{ "German", "Hallo Welt" },
	{ "Haitian Creole", "Bonjou Mond" },
	{ "Hungarian", "Hello Vilag" },
	{ "Icelandic", "Hallo Heimur" },
	{ "Indonesian", "Halo Dunia" },
	{ "Irish", "Dia duit a Dhomhain" },
	{ "Italian", "Ciao Mondo" },
	{ "Javanese", "Halo Jagad" },
	{ "Latin", "Salve Munde" },
	{ "Latvian", "Sveika Pasaule" },
	{ "Lithuanian", "Labas Pasauli" },
	{ "Malay", "Halo Dunia" },
	{ "Maltese", "Bongu Dinja" },
	{ "Norwegian", "Hei Verden" },
	{ "Polish", "Witaj Swiecie" },
	{ "Portuguese", "Ola Mundo" },
	{ "Romanian", "Salut Lume" },
	{ "Slovak", "Ahoj Svet" },
	{ "Slovene", "Zdravo Svet" },
	{ "Spanish", "Hola Mundo" },
	{ "Swahili", "Habari Dunia" },
	{ "Swedish", "Hej Varlden" },
	{ "Tagalog", "Kumusta Mundo" },
	{ "Turkish", "Merhaba Dunya" },
	{ "Vietnamese", "Xin chao The Gioi" },
	{ "Welsh", "Helo Byd" }
}

return language_table
